/* AUTO-GENERATED by scripts/gen-kuva-routes.mjs — Kuwaiti Virtual route
   network, anchored at Kuwait International (OKKK). Starts empty; routes are
   added by staff in the Crew Center. */

export type Route = {
  routeNumber: string;
  dep: string;
  arr: string;
  aircraft: string;
  minutes: number;
  airline: string;
};

export const ROUTES: Route[] = [];

/* Distinct airlines for the route-browser filter (mainline first). */
export const ROUTE_AIRLINES = ["Kuwaiti"] as const;
