/* AUTO-GENERATED by scripts/gen-kuva-routes.mjs — Kuwaiti Virtual route
   network, anchored at Kuwait International (OKBK). Mainline flights wear the KU
   code; codeshare legs carry the partner's flight number and airline. */

export type Route = {
  routeNumber: string;
  dep: string;
  arr: string;
  aircraft: string;
  minutes: number;
  airline: string;
};

export const ROUTES: Route[] = [
  {
    "routeNumber": "KU671/KU672",
    "dep": "OKBK",
    "arr": "OMDB",
    "aircraft": "Kuwaiti Airbus A320neo",
    "minutes": 80,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU615/KU616",
    "dep": "OKBK",
    "arr": "OTHH",
    "aircraft": "Kuwaiti Airbus A320neo",
    "minutes": 75,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU205/KU206",
    "dep": "OKBK",
    "arr": "OBBI",
    "aircraft": "Kuwaiti Airbus A320neo",
    "minutes": 55,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU181/KU182",
    "dep": "OKBK",
    "arr": "OOMS",
    "aircraft": "Kuwaiti Airbus A321neo",
    "minutes": 95,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU643/KU644",
    "dep": "OKBK",
    "arr": "OEJN",
    "aircraft": "Kuwaiti Airbus A321neo",
    "minutes": 130,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU611/KU612",
    "dep": "OKBK",
    "arr": "OERK",
    "aircraft": "Kuwaiti Airbus A320neo",
    "minutes": 90,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU561/KU562",
    "dep": "OKBK",
    "arr": "OEDF",
    "aircraft": "Kuwaiti Airbus A320neo",
    "minutes": 65,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU555/KU556",
    "dep": "OKBK",
    "arr": "OJAI",
    "aircraft": "Kuwaiti Airbus A321neo",
    "minutes": 150,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU531/KU532",
    "dep": "OKBK",
    "arr": "OLBA",
    "aircraft": "Kuwaiti Airbus A321neo",
    "minutes": 175,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU521/KU522",
    "dep": "OKBK",
    "arr": "ORBI",
    "aircraft": "Kuwaiti Airbus A320neo",
    "minutes": 70,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU383/KU384",
    "dep": "OKBK",
    "arr": "VIDP",
    "aircraft": "Kuwaiti Airbus A330-900neo",
    "minutes": 240,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU301/KU302",
    "dep": "OKBK",
    "arr": "VABB",
    "aircraft": "Kuwaiti Airbus A330-300",
    "minutes": 210,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU357/KU358",
    "dep": "OKBK",
    "arr": "OPKC",
    "aircraft": "Kuwaiti Airbus A320neo",
    "minutes": 150,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU371/KU372",
    "dep": "OKBK",
    "arr": "OPLA",
    "aircraft": "Kuwaiti Airbus A321neo",
    "minutes": 180,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU345/KU346",
    "dep": "OKBK",
    "arr": "VCBI",
    "aircraft": "Kuwaiti Airbus A330-300",
    "minutes": 300,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU339/KU340",
    "dep": "OKBK",
    "arr": "VGHS",
    "aircraft": "Kuwaiti Airbus A330-300",
    "minutes": 270,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU417/KU418",
    "dep": "OKBK",
    "arr": "WSSS",
    "aircraft": "Kuwaiti Airbus A330-800neo",
    "minutes": 420,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU411/KU412",
    "dep": "OKBK",
    "arr": "VTBS",
    "aircraft": "Kuwaiti Airbus A330-900neo",
    "minutes": 380,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU423/KU424",
    "dep": "OKBK",
    "arr": "WMKK",
    "aircraft": "Kuwaiti Airbus A330-800neo",
    "minutes": 425,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU437/KU438",
    "dep": "OKBK",
    "arr": "VHHH",
    "aircraft": "Kuwaiti Airbus A330-900neo",
    "minutes": 480,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU441/KU442",
    "dep": "OKBK",
    "arr": "RJTT",
    "aircraft": "Kuwaiti Boeing 777-300ER",
    "minutes": 600,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU541/KU542",
    "dep": "OKBK",
    "arr": "HECA",
    "aircraft": "Kuwaiti Airbus A330-300",
    "minutes": 240,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU567/KU568",
    "dep": "OKBK",
    "arr": "HKJK",
    "aircraft": "Kuwaiti Airbus A330-900neo",
    "minutes": 330,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU571/KU572",
    "dep": "OKBK",
    "arr": "HAAB",
    "aircraft": "Kuwaiti Airbus A330-300",
    "minutes": 300,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU101/KU102",
    "dep": "OKBK",
    "arr": "EGLL",
    "aircraft": "Kuwaiti Boeing 777-300ER",
    "minutes": 425,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU175/KU176",
    "dep": "OKBK",
    "arr": "LFPG",
    "aircraft": "Kuwaiti Airbus A330-800neo",
    "minutes": 410,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU165/KU166",
    "dep": "OKBK",
    "arr": "EDDF",
    "aircraft": "Kuwaiti Airbus A330-800neo",
    "minutes": 390,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU149/KU150",
    "dep": "OKBK",
    "arr": "LTFM",
    "aircraft": "Kuwaiti Airbus A330-300",
    "minutes": 270,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU185/KU186",
    "dep": "OKBK",
    "arr": "LIRF",
    "aircraft": "Kuwaiti Airbus A330-800neo",
    "minutes": 360,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU171/KU172",
    "dep": "OKBK",
    "arr": "EHAM",
    "aircraft": "Kuwaiti Airbus A330-800neo",
    "minutes": 410,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU161/KU162",
    "dep": "OKBK",
    "arr": "LGAV",
    "aircraft": "Kuwaiti Airbus A330-300",
    "minutes": 300,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU117/KU118",
    "dep": "OKBK",
    "arr": "KJFK",
    "aircraft": "Kuwaiti Boeing 777-300ER",
    "minutes": 780,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU107/KU108",
    "dep": "OKBK",
    "arr": "KIAD",
    "aircraft": "Kuwaiti Boeing 777-300ER",
    "minutes": 800,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU121/KU122",
    "dep": "OKBK",
    "arr": "KORD",
    "aircraft": "Kuwaiti Boeing 777-300ER",
    "minutes": 820,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "QR1087/QR1088",
    "dep": "OKBK",
    "arr": "OTHH",
    "aircraft": "Qatari Airbus A320",
    "minutes": 70,
    "airline": "Qatari"
  },
  {
    "routeNumber": "QR707/QR708",
    "dep": "OTHH",
    "arr": "WSSS",
    "aircraft": "Qatari Airbus A350-1000",
    "minutes": 455,
    "airline": "Qatari"
  },
  {
    "routeNumber": "EK856/EK857",
    "dep": "OKBK",
    "arr": "OMDB",
    "aircraft": "Emirates Boeing 777-300ER",
    "minutes": 80,
    "airline": "Emirates"
  },
  {
    "routeNumber": "EK1/EK2",
    "dep": "OMDB",
    "arr": "EGLL",
    "aircraft": "Emirates Airbus A380",
    "minutes": 445,
    "airline": "Emirates"
  },
  {
    "routeNumber": "SV576/SV577",
    "dep": "OKBK",
    "arr": "OEJN",
    "aircraft": "Saudia Airbus A330-300",
    "minutes": 130,
    "airline": "Saudia"
  },
  {
    "routeNumber": "WY648/WY649",
    "dep": "OKBK",
    "arr": "OOMS",
    "aircraft": "Oman Air Boeing 737 MAX 8",
    "minutes": 95,
    "airline": "Oman Air"
  },
  {
    "routeNumber": "RJ810/RJ811",
    "dep": "OKBK",
    "arr": "OJAI",
    "aircraft": "Royal Jordanian Airbus A320",
    "minutes": 150,
    "airline": "Royal Jordanian"
  },
  {
    "routeNumber": "MS610/MS611",
    "dep": "OKBK",
    "arr": "HECA",
    "aircraft": "EgyptAir Boeing 737-800",
    "minutes": 240,
    "airline": "EgyptAir"
  },
  {
    "routeNumber": "TK765/TK766",
    "dep": "OKBK",
    "arr": "LTFM",
    "aircraft": "Turkish Airbus A321neo",
    "minutes": 270,
    "airline": "Turkish"
  },
  {
    "routeNumber": "BA117/BA118",
    "dep": "EGLL",
    "arr": "KJFK",
    "aircraft": "British Airways Boeing 777-300ER",
    "minutes": 460,
    "airline": "British Airways"
  },
  {
    "routeNumber": "JL44/JL43",
    "dep": "RJTT",
    "arr": "KSFO",
    "aircraft": "Japan Airlines Boeing 777-300ER",
    "minutes": 575,
    "airline": "Japan Airlines"
  },
  {
    "routeNumber": "AA2400/AA2401",
    "dep": "KJFK",
    "arr": "KDFW",
    "aircraft": "American Airlines Boeing 737 MAX 8",
    "minutes": 240,
    "airline": "American"
  }
];

/* Distinct airlines for the route-browser filter (mainline first). */
export const ROUTE_AIRLINES = ["Kuwaiti","Qatari","Emirates","Saudia","Oman Air","Royal Jordanian","EgyptAir","Turkish","British Airways","Japan Airlines","American"] as const;
