/* AUTO-GENERATED by scripts/gen-kuva-routes.mjs — Kuwaiti Virtual route
   network, anchored at Kuwait International (OKKK). Mainline flights wear the KU
   code; codeshare legs carry the partner's flight number and airline. */

export type Route = {
  routeNumber: string;
  dep: string;
  arr: string;
  aircraft: string;
  minutes: number;
  airline: string;
};

export const ROUTES: Route[] = [
  {
    "routeNumber": "KU611/KU612",
    "dep": "OKKK",
    "arr": "OERK",
    "aircraft": "Kuwaiti Airbus A320neo",
    "minutes": 90,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU615/KU616",
    "dep": "OKKK",
    "arr": "OEJN",
    "aircraft": "Kuwaiti Airbus A321neo",
    "minutes": 130,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU617/KU618",
    "dep": "OKKK",
    "arr": "OEMA",
    "aircraft": "Kuwaiti Airbus A321neo",
    "minutes": 135,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU561/KU562",
    "dep": "OKKK",
    "arr": "OEDF",
    "aircraft": "Kuwaiti Airbus A320neo",
    "minutes": 65,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU671/KU672",
    "dep": "OKKK",
    "arr": "OMDB",
    "aircraft": "Kuwaiti Airbus A320neo",
    "minutes": 80,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU673/KU674",
    "dep": "OKKK",
    "arr": "OMAA",
    "aircraft": "Kuwaiti Airbus A320neo",
    "minutes": 85,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU205/KU206",
    "dep": "OKKK",
    "arr": "OBBI",
    "aircraft": "Kuwaiti Airbus A320neo",
    "minutes": 55,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU181/KU182",
    "dep": "OKKK",
    "arr": "OOMS",
    "aircraft": "Kuwaiti Airbus A321neo",
    "minutes": 95,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU541/KU542",
    "dep": "OKKK",
    "arr": "OJAI",
    "aircraft": "Kuwaiti Airbus A321neo",
    "minutes": 150,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU551/KU552",
    "dep": "OKKK",
    "arr": "OLBA",
    "aircraft": "Kuwaiti Airbus A321neo",
    "minutes": 175,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU525/KU526",
    "dep": "OKKK",
    "arr": "ORMM",
    "aircraft": "Kuwaiti Airbus A320neo",
    "minutes": 50,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU521/KU522",
    "dep": "OKKK",
    "arr": "ORBI",
    "aircraft": "Kuwaiti Airbus A320neo",
    "minutes": 70,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU663/KU664",
    "dep": "OKKK",
    "arr": "OIIE",
    "aircraft": "Kuwaiti Airbus A320neo",
    "minutes": 100,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU677/KU678",
    "dep": "OKKK",
    "arr": "OISS",
    "aircraft": "Kuwaiti Airbus A320neo",
    "minutes": 85,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU169/KU170",
    "dep": "OKKK",
    "arr": "LTFM",
    "aircraft": "Kuwaiti Airbus A330-300",
    "minutes": 245,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU173/KU174",
    "dep": "OKKK",
    "arr": "LTAI",
    "aircraft": "Kuwaiti Airbus A321neo",
    "minutes": 250,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU543/KU544",
    "dep": "OKKK",
    "arr": "HECA",
    "aircraft": "Kuwaiti Airbus A330-300",
    "minutes": 170,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU381/KU382",
    "dep": "OKKK",
    "arr": "VIDP",
    "aircraft": "Kuwaiti Airbus A330-300",
    "minutes": 250,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU301/KU302",
    "dep": "OKKK",
    "arr": "VABB",
    "aircraft": "Kuwaiti Airbus A330-300",
    "minutes": 225,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU385/KU386",
    "dep": "OKKK",
    "arr": "VAAH",
    "aircraft": "Kuwaiti Airbus A321neo",
    "minutes": 230,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU387/KU388",
    "dep": "OKKK",
    "arr": "VOHS",
    "aircraft": "Kuwaiti Airbus A330-300",
    "minutes": 270,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU383/KU384",
    "dep": "OKKK",
    "arr": "VOMM",
    "aircraft": "Kuwaiti Airbus A330-300",
    "minutes": 285,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU389/KU390",
    "dep": "OKKK",
    "arr": "VOCI",
    "aircraft": "Kuwaiti Airbus A330-300",
    "minutes": 290,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU391/KU392",
    "dep": "OKKK",
    "arr": "VOTV",
    "aircraft": "Kuwaiti Airbus A330-300",
    "minutes": 300,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU351/KU352",
    "dep": "OKKK",
    "arr": "OPKC",
    "aircraft": "Kuwaiti Airbus A320neo",
    "minutes": 135,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU357/KU358",
    "dep": "OKKK",
    "arr": "OPLA",
    "aircraft": "Kuwaiti Airbus A321neo",
    "minutes": 165,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU361/KU362",
    "dep": "OKKK",
    "arr": "OPIS",
    "aircraft": "Kuwaiti Airbus A321neo",
    "minutes": 165,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU371/KU372",
    "dep": "OKKK",
    "arr": "VGHS",
    "aircraft": "Kuwaiti Airbus A330-300",
    "minutes": 285,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU345/KU346",
    "dep": "OKKK",
    "arr": "VCBI",
    "aircraft": "Kuwaiti Airbus A330-300",
    "minutes": 290,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU411/KU412",
    "dep": "OKKK",
    "arr": "VTBS",
    "aircraft": "Kuwaiti Airbus A330-800neo",
    "minutes": 395,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU421/KU422",
    "dep": "OKKK",
    "arr": "ZGGG",
    "aircraft": "Kuwaiti Airbus A330-900neo",
    "minutes": 480,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU415/KU416",
    "dep": "OKKK",
    "arr": "RPLL",
    "aircraft": "Kuwaiti Airbus A330-900neo",
    "minutes": 560,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU101/KU102",
    "dep": "OKKK",
    "arr": "EGLL",
    "aircraft": "Kuwaiti Boeing 777-300ER",
    "minutes": 395,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU165/KU166",
    "dep": "OKKK",
    "arr": "EDDF",
    "aircraft": "Kuwaiti Airbus A330-800neo",
    "minutes": 360,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU175/KU176",
    "dep": "OKKK",
    "arr": "LFPG",
    "aircraft": "Kuwaiti Airbus A330-800neo",
    "minutes": 375,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU185/KU186",
    "dep": "OKKK",
    "arr": "LIRF",
    "aircraft": "Kuwaiti Airbus A330-800neo",
    "minutes": 330,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU167/KU168",
    "dep": "OKKK",
    "arr": "LSGG",
    "aircraft": "Kuwaiti Airbus A330-800neo",
    "minutes": 360,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU187/KU188",
    "dep": "OKKK",
    "arr": "LEMD",
    "aircraft": "Kuwaiti Airbus A330-800neo",
    "minutes": 420,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU117/KU118",
    "dep": "OKKK",
    "arr": "KJFK",
    "aircraft": "Kuwaiti Boeing 777-300ER",
    "minutes": 785,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU103/KU104",
    "dep": "EGLL",
    "arr": "KJFK",
    "aircraft": "Kuwaiti Boeing 777-300ER",
    "minutes": 460,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "KU417/KU418",
    "dep": "VTBS",
    "arr": "RPLL",
    "aircraft": "Kuwaiti Airbus A330-800neo",
    "minutes": 210,
    "airline": "Kuwaiti"
  },
  {
    "routeNumber": "QR1087/QR1088",
    "dep": "OKKK",
    "arr": "OTHH",
    "aircraft": "Qatari Airbus A320",
    "minutes": 70,
    "airline": "Qatari"
  },
  {
    "routeNumber": "EK856/EK857",
    "dep": "OKKK",
    "arr": "OMDB",
    "aircraft": "Emirates Boeing 777-300ER",
    "minutes": 80,
    "airline": "Emirates"
  },
  {
    "routeNumber": "SV576/SV577",
    "dep": "OKKK",
    "arr": "OEJN",
    "aircraft": "Saudia Airbus A330-300",
    "minutes": 130,
    "airline": "Saudia"
  },
  {
    "routeNumber": "MS610/MS611",
    "dep": "OKKK",
    "arr": "HECA",
    "aircraft": "EgyptAir Boeing 737-800",
    "minutes": 170,
    "airline": "EgyptAir"
  },
  {
    "routeNumber": "TK765/TK766",
    "dep": "OKKK",
    "arr": "LTFM",
    "aircraft": "Turkish Airbus A321neo",
    "minutes": 245,
    "airline": "Turkish"
  },
  {
    "routeNumber": "BA117/BA118",
    "dep": "EGLL",
    "arr": "KJFK",
    "aircraft": "British Airways Boeing 777-300ER",
    "minutes": 460,
    "airline": "British Airways"
  }
];

/* Distinct airlines for the route-browser filter (mainline first). */
export const ROUTE_AIRLINES = ["Kuwaiti","Qatari","Emirates","Saudia","EgyptAir","Turkish","British Airways"] as const;
